"""Feature table shared by classify_gap.py and classify_gated.py.

Each entry is (feature id, verdict, regex on the OsaurusCore-relative path);
the first match wins. Verdicts: I = incompatible (Apple Silicon only /
upstream-only artifact), C = covered by Intel's own implementation, W = needs
work, N = not a user feature. Every W id has a row in
docs/INTEL_MISSING_FEATURES_BACKLOG.md.
"""

F=[
("INC-mlx","I",r"ModelRuntime|MLX|Services/Inference/(MLXService|ModelService)|ModelDownloadService|Managers/Model/(ModelManager|ModelManifestUpdates|ModelUpdatePolling|ModelPickerItemCache)|HuggingFace|ModelManifest|ModelFileIntegrity|BundledModelSeeder|ChipProfile|GPUMemoryBudget|SwapPressureMonitor|MemoryPressureResponder|ModelWarmup|WarmupProgressHub|ChatWarmupController|ChatSessionWarmup|MTP|DiskCache|SafeDiskCachePurge|LocalVisionEvidence|EmbeddingDetection|VLMDetection|ModelFormatDetection|Safetensors|ModelSizeCache|ModelMemoryTelemetry|ModelCapabilityLedger|ModelPrefillTuning|ParentResidency|RuntimeProof|PrefillDebugLog|GenerationOutputRelay|DecodePerformanceSection|MemorySafetySection|LocalGenerationDefaults|LocalReasoningCapability|DeclaredReasoningEffort|AlignmentPreparationState|OnboardingModelsProxy|BrainSource|ModelListRow|SystemStatusBar|SwiftTransformersTokenizer|InferenceFeatureFlags|RuntimeConfig|GenerationEventMapper|MetalSafeEmbedder|ModelMetadataCache|ImageGenerationService|ImageGenerationTypes|ImageJobCancellation|ImageModelDownloadService|ImageModelsDownloadView|MLXErrorRecovery|ServerRuntimeSettingsStore|InstalledVisionEvaluation|AppleScriptModelCatalog|AppleScriptModelsView|ResidencyHandoff|SubagentResidency|AppleScriptWarmResidency|ChatResidencyHandoff|AuxiliaryModelHandoff|AdmissionPositionLimit|SubagentAdmission|SubagentBatchAdmissionPlanner|FoundationModelService|NativeImageJobCoordinator|NativeImageToolArtifactBridge|NativeImageTools|ImageGenerationView|ImageGenerationPanelView|ChunkedFileDownloader|LiveVoiceAudioInputRegistry|ModelSSDResidency"),
("INC-containers","I",r"Services/Sandbox/(SandboxManager|SandboxAgentProvisioner|SandboxEgressPolicy|SandboxPackage|SandboxPluginRegistration|SandboxProvisioningDiagnostics|SandboxResumableDownloader|SandboxRootfs|SandboxRuntimeAssets|SandboxSecurity|SandboxStartupMetrics|SandboxToolRegistrar|SandboxToolRequestContext|SandboxWorkspaceChange|LiveExecSink|TeeWriter)|SandboxEgressProxy|Plugin/SandboxPlugin|SandboxPlugin|SandboxSecretTools|BuiltinSandboxTools|SandboxStdioRunner|WorkspaceShareRoute|WorkspaceInspectPayload|ShellMutationPlanner"),
("INC-upstream-only","I",r"ProductHuntLaunchCampaign|MockAppleScriptWorld|MockMacDriver|MockChatData"),
("W-methods","W",r"Services/Method/|Storage/MethodDatabase"),
("COV-tool-discovery","C",r"Services/Tool/(ToolIndexService|ToolSearchService)|Services/Skill/SkillSearchService|Services/Context/(CapabilitySearchHealth|SessionToolStateStore|CapabilitySearchEvaluator)|Storage/ToolDatabase|CapabilityQueryIntent"),
("W-description-backfill","W",r"AgentDescriptionBackfill|AgentDescriptionGenerator"),
("N-dev-tooling","N",r"Services/Context/.*Evaluat|EvalHarness|EvalPairedRunIsolation|PromptComposerExperiment|Previews\.swift$"),
("W-settings-ux-2950","W",r"Views/Settings/(CommandLineToolSection|Shared/SettingsKit|ChatSettingsView|MCPProviderDirectoryView)|Views/SlashCommand/SlashCommandEditorSheet|Views/Voice/(ChatVoiceSettingsTab|VoiceSharedComponents|TranscriptionSettingsTab)|Views/Tool/ToolAutoAllowToggle"),
("COV-intel-own","C",r"Managers/AgentManager\.swift|Models/Agent/AgentStore|Services/Chat/(ChatEngine|ChatEngineProtocol|SystemPromptComposer|AgentToolLoop|ContextBudgetManager|ComposeRequest|PromptBuilder|PromptManifest|ResolvedToolset|AgentConfigSnapshot|ContextSizeClass|AgentNameDetector|ContextCompactionService|CompactionWatermark|ChatTitleService|AgentReasoningPolicy)|Tools/ToolRegistry\.swift|Models/Chat/(ChatTurn|ChatTurnData|ContentBlock|ChatSessionData|ChatSessionStore|ChatConfiguration|SessionSource|ResponseWriters|SessionCapability)|Managers/BlockMemoizer|Managers/Chat/ChatSessionsManager|Managers/RemoteProviderManager|Services/Provider/(RemoteProviderService|RemoteReasoningPolicy|RemoteToolDetection)|Models/API/(OpenAIAPI|AnthropicAPI|GeminiAPI|OpenResponsesAPI)|Storage/(ChatHistoryDatabase|ChatHistoryWriter|OsaurusStorageOpener|StorageEncryptionPolicy|StorageFile|StorageFileFormat|StorageFormatConverter|StorageMigrationCoordinator|StorageMutationGate|StorageDatabaseCatalog)|Networking/(ServerController|BonjourAdvertiser)|Services/Memory/(MemoryService|MemorySearchService|MemoryConsolidator|DistillationCoordinator|MemoryContextAssembler|MemoryDiagnostics|MemoryPlanner|EmbeddingService|MemoryManagementConsoleService)|Models/Memory/MemoryManagementConsoleModels|Views/Memory/MemoryManagementConsoleView|Managers/SkillManager|Services/Inference/(ClaudeCodeService|ClaudeCodeBridgeGrantStore|CoreModelService)|Managers/WindowManager|Services/NotificationService|Services/DirectoryPickerService|Models/Configuration/AppConfiguration|Models/Chat/ChatConfigurationStore|Utils/ActivityTracker|Managers/ThreadCache|Utils/StreamingDeltaProcessor|Services/Keychain/AgentSecretsKeychain|Views/Router/RouterAccountUsageCenter|Services/Chat/AgentAbilityContextPreview|Views/Agent/AgentAbilitiesOverviewView|Services/Plugin/PluginHostAPI|Services/Plugin/PluginInstructionsResolver|Services/Plugin/PluginRepositoryService|Services/Themes/ThemeShareService|Services/Themes/ThemesDeepLinkRouter|Services/SearchService|Models/Chat/LegacySessionImporter|Services/MCP/MCPServerManager|Storage/PluginDatabase|Networking/HTTP(LoopHelpers|ProtocolErrors|RequestParse)|Managers/ManagementBadgeStore"),
("W-subagents","W",r"Subagent|AgentDelegation|SpawnAgentTool|SpawnConfigurationEditor|SubagentSettingsSection|SubagentFeedView|SubagentBackgroundTaskBridge|DelegationRecord|SpawnBatchConcurrency"),
("W-computer-use","W",r"ComputerUse|ScreenContextPreview|CloudVisionConsent"),
("W-browser-use","W",r"Browser"),
("W-applescript-agent","W",r"AppleScript/|MacQueryTool"),
("W-privacy-filter","W",r"PrivacyFilter|Redaction(Highlighter|HoverController)|SecretScrubber"),
("W-channels","W",r"AgentChannel|ChannelActivityLogger|Services/(Slack|Telegram|Discord|WhatsApp|IMessage|Channels)/|Models/(Slack|Telegram|Discord|WhatsApp|IMessage|Channels)/|N8n|OsaurusRunningInstanceInspector|Storage/AgentChannelMessageStore|Views/Settings/(Slack|Telegram|Discord|WhatsApp|IMessage)SettingsView|ConfigChannelDetails"),
("W-workspaces-identity-mobile","W",r"ModelOptionsSnapshot|PeerInferenceSharing|Workspace|Router/|OsaurusID|Identity/|MobileConnect|Pairing|RelayTunnel|SecureChannel|OwnerDeviceAccessHost|RemoteAgentManager|AgentInvite|AgentSharedWithSection|PeerCallNotifier|BonjourBrowser|HostAPIBridgeServer|OsaurusConnectView|LocalNetworkAddress|SharedEventLoopGroups|HTTPCallerContext|AgentRunUsage|RemoteSessionContinuation|RemoteSecretPromptQueue|RemoteRunArtifacts|AgentCollaboration|HostedRunNotice|RemoteAgentRunLog"),
("W-declarative-config","W",r"Configuration/Declarative|Tools/Configuration|Tools/ConfigurationTools|ConfigApprovalModal|OrchestratorSupportSections"),
("W-file-history","W",r"FileHistory|FileChangesPanel|FileDiff|NativeFileDiffView|ChatHistoryPane|ChatInspectorPanel|ProjectInspectorPanel|ProjectDetailView|FileHistoryRetentionSection"),
("W-doc-editing","W",r"Services/Documents/|FileCopyTool"),
("W-chat-tabs","W",r"ChatTab|ThreadScrollPosition|LiveChatSessionRegistry|SessionActivityMonitor|NewAgentHighlightStore"),
("W-chat-export","W",r"ChatSessionExport|ChatExportOptions"),
("W-voice","W",r"Speech|TTSService|OpenAICompatibleTTSClient|Transcription|VAD|LiveVoiceAudio|Models/Voice|Services/Voice"),
("W-knowledge-write","W",r"Knowledge(Write|Curation|Diff|FolderWatcher|GitSync|LinkResolver|TypeInference)|KnowledgeWriteLogDatabase|Views/Knowledge/"),
("W-skills-plugins-import","W",r"Skill|ClaudeMarketplace|ClaudePlugin|GitHubImportSheet|GitHubTokenViews|GitHubAuth|PluginProcessHost|PluginHost/main|ExternalTool"),
("W-media-generation","W",r"MediaGeneration|VideoTool|ImageAPI"),
("W-agent-loop-tools","W",r"AgentLoopTools|AgentTaskState|RunProgress|StreamRepetitionDetector|ToolOutputCaps|ToolOutputCompressor|ToolExecutionScope|SchemaValidator|ToolWirePropertyOrder|CurrentTimeTool|SubagentApprovalArguments|Grounded.*Check|ToolResultMediaBridge|ChatErrorMessages|ChatTurnGenerationControls"),
("W-tool-catalog-ui","W",r"ToolDisplayName|Views/Tool/|Models/Tool/|ToolAvailabilityBadge|CapabilityTools|CapabilityQueryIntent|AgentCapabilityReadiness"),
("W-chat-ux","W",r"AtFile|ChatCrossSelection|ChatInputHistory|FollowUpSuggestion|CompactionDialogView|NativeCompactionMarkerView|NativeActivityGroupView|NativeDispatchBadgeRow|DispatchEnvelope|ShimmerLabel|RecentFoldersPanel|ImportGuideSheet|ImportHistoryPromptGate|ChatPersistenceNotice|MarkdownBlockParsing|MarkdownDocumentView|IMEAwareTextField|ScreenshotCaptureService|SlashCommandRegistry|WorkspaceFileReference|WorkspaceSessionContext|AgentDispatchTarget|BuiltInAgentGuard|Views/Agent/AgentDetailChrome|ContextAttribution"),
("W-server-api","W",r"ServerModelsTabContent|InferenceActivityRegistry|Networking/|MCPServerHub|ModelExposureStore|EvidenceReport|Services/Auth/"),
("W-mcp-providers","W",r"Services/MCP/"),
("W-providers-ux","W",r"Provider|FireworksAPI|CodexCLIConfiguration|FavoriteModelsStore|WireTransportProbe"),
("W-self-scheduling","W",r"SchedulerTools|Schedule"),
("W-tools-misc","W",r"RenderChartTool|SearchMemoryTool|ShareArtifactTool|SharedArtifact|RedactionTool|ShellSandboxProfile|Seatbelt"),
("W-storage-health","W",r"PersistenceHealth|StorageRecoveryService|FileVaultStatus|StorageLocationStandards|ConfigDiskWriter"),
("W-diagnostics-telemetry","W",r"ProcessCpuProbe|ProcessMemoryProbe|OnboardingTelemetry|CrashReporting|FeatureTelemetry|TelemetryService|SupportDiagnosticsBundle|TerminationForensics|ConsoleLogFile|MainThreadOperationLedger|AsyncDeadline"),
("W-ui-misc","W",r"Views/Common/|Views/Onboarding/|ThemeLibraryManagement|SystemAccentColor|OsaurusGuide|AgentRunPowerManager|Views/Tour/|WhatsNewHero|RedeemRetryCountdownHint|KeychainServices|SecretAvailability|SecretSaveOutcome|OsaurusKeychain|Search/SearchStructuredDataStore|Views/Settings/(BrowserSettingsView|ComputerUse)|Services/Keychain/"),
]
