//
//  MemoryModels.swift
//  osaurus
//
//  Data types for the v2 memory system.
//
//  Three persistent layers, plus a transcript fallback:
//
//    1. Identity   — single row of stable user facts (auto-derived + explicit overrides)
//    2. PinnedFact — promoted, salience-scored facts with decay and use tracking
//    3. Episode    — per-session digest (summary, topics, decisions, entities, salience)
//    -. Transcript — raw turns, kept only for fallback retrieval
//
//  Per-turn extraction and the 7-type MemoryEntry enum from the v1 system are gone.
//  Distillation runs once per session, not per turn.
//

import Foundation

// MARK: - Layer 1: Identity

/// Stable user identity. Single row, regenerated lazily from explicit
/// overrides plus the most-salient pinned facts. The auto-derived `content`
/// is regenerated by the consolidator; `overrides` are user-authored and
/// always take precedence in context assembly.
public struct Identity: Codable, Sendable {
    /// Auto-derived narrative summary of who the user is. May be empty
    /// before the first consolidation pass runs.
    public var content: String
    /// Explicit user-authored facts that always appear in context. Listed
    /// before the auto-derived content during assembly.
    public var overrides: [String]
    /// Approximate token count of `content` (overrides are tiny so we don't
    /// budget them separately).
    public var tokenCount: Int
    /// Bumped each time the auto-derived `content` is regenerated.
    public var version: Int
    /// Model used for the most recent regeneration (or "user" when manually edited).
    public var model: String
    /// ISO8601 timestamp of the most recent regeneration.
    public var generatedAt: String

    public init(
        content: String = "",
        overrides: [String] = [],
        tokenCount: Int = 0,
        version: Int = 0,
        model: String = "",
        generatedAt: String = ""
    ) {
        self.content = content
        self.overrides = overrides
        self.tokenCount = tokenCount
        self.version = version
        self.model = model
        self.generatedAt = generatedAt
    }
}

// MARK: - Layer 2: Pinned Facts

/// A salience-scored fact promoted from one or more episodes. Replaces the
/// v1 `MemoryEntry` 7-type taxonomy with a single, ranked pool.
public struct PinnedFact: Codable, Sendable, Identifiable {
    public var id: String
    public var agentId: String
    public var content: String
    /// Relevance/importance score in [0, 1]. Decayed by the consolidator
    /// (`score *= exp(-Δdays / halfLife)`) and incremented when the fact
    /// is referenced by a new episode or surfaced in context.
    public var salience: Double
    /// Number of episodes that reference this fact (used by the consolidator
    /// to decide whether to promote a candidate to the pinned pool).
    public var sourceCount: Int
    /// Optional source episode ID — the episode that first promoted this fact.
    public var sourceEpisodeId: Int?
    /// ISO8601 timestamp of the most recent retrieval / context surface.
    public var lastUsed: String
    /// Bumped each time the fact is included in an assembled context.
    public var useCount: Int
    /// `active` | `evicted`. Evicted rows are kept briefly for audit before
    /// the consolidator hard-deletes them.
    public var status: String
    /// ISO8601 timestamp of insertion.
    public var createdAt: String
    /// Optional comma-separated keyword tags (lightweight; not used for
    /// ranking, only for UI filtering).
    public var tagsCSV: String?

    public var tags: [String] {
        guard let tagsCSV, !tagsCSV.isEmpty else { return [] }
        return tagsCSV.split(separator: ",").map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
    }

    public init(
        id: String = UUID().uuidString,
        agentId: String,
        content: String,
        salience: Double = 0.5,
        sourceCount: Int = 1,
        sourceEpisodeId: Int? = nil,
        lastUsed: String = "",
        useCount: Int = 0,
        status: String = "active",
        createdAt: String = "",
        tagsCSV: String? = nil
    ) {
        self.id = id
        self.agentId = agentId
        self.content = String(content.prefix(MemoryConfiguration.maxContentLength))
        self.salience = min(1.0, max(0.0, salience))
        self.sourceCount = max(0, sourceCount)
        self.sourceEpisodeId = sourceEpisodeId
        self.lastUsed = lastUsed
        self.useCount = max(0, useCount)
        self.status = status
        self.createdAt = createdAt
        self.tagsCSV = tagsCSV
    }
}

// MARK: - Layer 3: Episodes

/// A per-session digest. Replaces both the v1 `ConversationSummary` and the
/// per-turn `MemoryEntry` extraction. One episode is produced per session by
/// `MemoryService.distillSession`, and contains everything the planner needs
/// to surface "what did we talk about" without going to the raw transcript.
public struct Episode: Codable, Sendable, Identifiable {
    public var id: Int
    public var agentId: String
    public var conversationId: String
    /// One- to three-sentence narrative summary of the session.
    public var summary: String
    /// Comma-separated topics, in order of relevance.
    public var topicsCSV: String
    /// Comma-separated entity names mentioned (people, projects, tools, …).
    /// Used by the relevance gate for entity-name hits.
    public var entitiesCSV: String
    /// Bullet-style decision list (newline-separated). Empty when the
    /// session didn't decide anything.
    public var decisions: String
    /// Bullet-style action items (newline-separated).
    public var actionItems: String
    /// Salience score in [0, 1]; decayed by the consolidator and used by
    /// the planner when picking which episodes to surface.
    public var salience: Double
    public var tokenCount: Int
    public var model: String
    /// ISO8601 timestamp of when the conversation actually happened (the
    /// session date, not the distillation date).
    public var conversationAt: String
    public var status: String
    /// ISO8601 timestamp of when the episode was distilled.
    public var createdAt: String

    public var topics: [String] {
        topicsCSV.split(separator: ",").map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
    }

    public var entities: [String] {
        entitiesCSV.split(separator: ",").map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
    }

    public init(
        id: Int = 0,
        agentId: String,
        conversationId: String,
        summary: String,
        topicsCSV: String = "",
        entitiesCSV: String = "",
        decisions: String = "",
        actionItems: String = "",
        salience: Double = 0.5,
        tokenCount: Int = 0,
        model: String = "",
        conversationAt: String,
        status: String = "active",
        createdAt: String = ""
    ) {
        self.id = id
        self.agentId = agentId
        self.conversationId = conversationId
        self.summary = String(summary.prefix(MemoryConfiguration.maxContentLength))
        self.topicsCSV = topicsCSV
        self.entitiesCSV = entitiesCSV
        self.decisions = decisions
        self.actionItems = actionItems
        self.salience = min(1.0, max(0.0, salience))
        self.tokenCount = max(0, tokenCount)
        self.model = model
        self.conversationAt = conversationAt
        self.status = status
        self.createdAt = createdAt
    }
}

// MARK: - Transcript (raw turns; fallback retrieval only)

/// A single conversation turn. Renamed from v1's `ConversationChunk`. Kept
/// for retrieval fallback — never injected into the default context block.
public struct TranscriptTurn: Codable, Sendable, Identifiable {
    public var id: Int
    public var conversationId: String
    public var chunkIndex: Int
    public var role: String
    public var content: String
    public var tokenCount: Int
    public var createdAt: String
    public var agentId: String
    public var conversationTitle: String?

    public init(
        id: Int = 0,
        conversationId: String,
        chunkIndex: Int,
        role: String,
        content: String,
        tokenCount: Int,
        createdAt: String = "",
        agentId: String = "",
        conversationTitle: String? = nil
    ) {
        self.id = id
        self.conversationId = conversationId
        self.chunkIndex = chunkIndex
        self.role = role
        self.content = content
        self.tokenCount = tokenCount
        self.createdAt = createdAt
        self.agentId = agentId
        self.conversationTitle = conversationTitle
    }
}

// MARK: - Background Processing

/// Buffered conversation turn awaiting end-of-session distillation. The
/// write path inserts these and never blocks; the distiller drains them.
public struct PendingSignal: Codable, Sendable {
    public var id: Int
    public var agentId: String
    public var conversationId: String
    public var userMessage: String
    public var assistantMessage: String?
    public var status: String
    public var createdAt: String

    public init(
        id: Int = 0,
        agentId: String,
        conversationId: String,
        userMessage: String,
        assistantMessage: String? = nil,
        status: String = "pending",
        createdAt: String = ""
    ) {
        self.id = id
        self.agentId = agentId
        self.conversationId = conversationId
        self.userMessage = userMessage
        self.assistantMessage = assistantMessage
        self.status = status
        self.createdAt = createdAt
    }
}

public struct ProcessingStats: Sendable {
    public var totalCalls: Int = 0
    public var avgDurationMs: Int = 0
    public var successCount: Int = 0
    public var errorCount: Int = 0
    public var skippedCount: Int = 0
    public var emptyCount: Int = 0
    public var deadLetterCount: Int = 0
}

/// Structured result of a single `MemoryService.distillSession` /
/// `performDistillSession` run. Returned so callers (notably the
/// `POST /memory/ingest` handler) can report what actually happened
/// instead of guessing from a fire-and-forget `Task`. Before this existed
/// the handler returned `{"status":"ok"}` even when distillation was
/// silently skipped (issue #1632): the heavy non-resident core-model gate
/// short-circuited the coordinator with no `processing_log` row at all.
public enum DistillOutcome: Sendable, Equatable {
    /// An episode was written. `pinned` / `identityFacts` are the counts
    /// promoted from this session.
    case distilled(episodeId: Int, pinned: Int, identityFacts: Int)
    /// No `pending` signals for the conversation (already distilled, or
    /// nothing was buffered).
    case noSignals
    /// A pre-LLM or transient gate skipped the run without erroring.
    /// `reason` is a stable token: `memory_disabled`, `not_resident`,
    /// `core_model_unset`, `core_model_unavailable`, `breaker_open`,
    /// `low_novelty:<n>chars`, `cancelled`.
    case skipped(reason: String)
    /// The model ran but produced no usable episode. `reason` is
    /// `no_episode` or `empty_summary`. Terminal: the signals are marked
    /// processed so the session is not retried.
    case empty(reason: String)
    /// The session failed `attempts` times and was dead-lettered; its
    /// signals will no longer be retried.
    case deadLettered(attempts: Int)
    /// A retryable error occurred (signals stay `pending` until the
    /// attempt cap is reached).
    case error(String)

    /// Compact, machine-readable status token for the `/memory/ingest`
    /// JSON body (`"distilled" | "skipped:<reason>" | "empty:<reason>" |
    /// "dead_letter:<attempts>" | "error:<msg>" | "no_signals"`).
    public var apiStatus: String {
        switch self {
        case .distilled: return "distilled"
        case .noSignals: return "no_signals"
        case .skipped(let reason): return "skipped:\(reason)"
        case .empty(let reason): return "empty:\(reason)"
        case .deadLettered(let attempts): return "dead_letter:\(attempts)"
        case .error(let msg): return "error:\(msg)"
        }
    }

    /// The episode primary key when a row was written, else nil.
    public var episodeId: Int? {
        if case .distilled(let id, _, _) = self { return id }
        return nil
    }
}

/// One row from `processing_log`. Surfaces what every distillation /
/// consolidation pass actually did — including the new `"skipped"` rows
/// that the distill pipeline writes when it bails before reaching the
/// model. The Memory diagnostics panel renders the last N of these so
/// support / users can see why an episode wasn't produced.
public struct ProcessingLogRow: Sendable, Identifiable {
    public var id: Int
    public var agentId: String
    public var taskType: String
    public var model: String?
    public var status: String
    public var details: String?
    public var inputTokens: Int?
    public var outputTokens: Int?
    public var durationMs: Int?
    public var createdAt: String

    public init(
        id: Int,
        agentId: String,
        taskType: String,
        model: String?,
        status: String,
        details: String?,
        inputTokens: Int?,
        outputTokens: Int?,
        durationMs: Int?,
        createdAt: String
    ) {
        self.id = id
        self.agentId = agentId
        self.taskType = taskType
        self.model = model
        self.status = status
        self.details = details
        self.inputTokens = inputTokens
        self.outputTokens = outputTokens
        self.durationMs = durationMs
        self.createdAt = createdAt
    }
}

/// Aggregate snapshot of `pending_signals` rows. "Are we buffering
/// anything at all?" is the fastest way to localise a memory-not-building
/// bug to the buffer step vs the distill step.
///
/// `totalSignals` / `distinctConversations` are pending rows only
/// (status='pending'). `processedSignals` and `deadLetteredSignals`
/// count retained signal rows in those statuses. `allTimeSignals` is the
/// full count regardless of status: when `allTimeSignals == 0` the chat
/// code never reached `bufferTurn` at all; when it's non-zero but
/// `totalSignals == 0` every signal has either been distilled, purged, or
/// dead-lettered.
public struct PendingSignalsSummary: Sendable {
    public var totalSignals: Int
    public var distinctConversations: Int
    public var processedSignals: Int
    public var deadLetteredSignals: Int
    public var allTimeSignals: Int

    public init(
        totalSignals: Int = 0,
        distinctConversations: Int = 0,
        processedSignals: Int = 0,
        deadLetteredSignals: Int = 0,
        allTimeSignals: Int = 0
    ) {
        self.totalSignals = totalSignals
        self.distinctConversations = distinctConversations
        self.processedSignals = processedSignals
        self.deadLetteredSignals = deadLetteredSignals
        self.allTimeSignals = allTimeSignals
    }
}

/// Snapshot of `MemoryService`'s buffer-path telemetry. Exists so the
/// diagnostics panel can answer the *only* question that matters when
/// `pending_signals` is empty AND `processing_log` is empty:
/// "did `bufferTurn` ever run, or did the chat code never call it?"
///
/// All counters are reset in-process only; they don't survive a relaunch.
/// That's intentional — a stale "1234 attempts" from yesterday tells us
/// nothing useful about today's broken state.
public struct BufferTurnTelemetry: Sendable {
    public var attempts: Int = 0
    public var insertSuccesses: Int = 0
    public var earlyReturnsEmptyMessage: Int = 0
    public var earlyReturnsDisabled: Int = 0
    public var insertFailures: Int = 0
    public var lastError: String?
    public var lastAttemptAt: Date?
    public var lastSuccessAt: Date?

    public init() {}
}

/// Progress reported by `MemoryService.backfillFromChatHistory`.
/// `stage = .buffering` while we walk chat-history sessions and write
/// `pending_signals`; `.distilling` while `syncNow()` drains them; `.done`
/// when the entire backfill finishes (or is cancelled).
public struct MemoryBackfillProgress: Sendable {
    public enum Stage: String, Sendable { case buffering, distilling, done, cancelled }
    public var stage: Stage
    public var sessionsTotal: Int
    public var sessionsProcessed: Int
    public var sessionsSkipped: Int
    public var turnsBuffered: Int
    public var lastSessionTitle: String?

    public init(
        stage: Stage = .buffering,
        sessionsTotal: Int = 0,
        sessionsProcessed: Int = 0,
        sessionsSkipped: Int = 0,
        turnsBuffered: Int = 0,
        lastSessionTitle: String? = nil
    ) {
        self.stage = stage
        self.sessionsTotal = sessionsTotal
        self.sessionsProcessed = sessionsProcessed
        self.sessionsSkipped = sessionsSkipped
        self.turnsBuffered = turnsBuffered
        self.lastSessionTitle = lastSessionTitle
    }
}

// MARK: - Memory Namespace

/// Typed wrapper over the string key that partitions every memory store
/// (episodes, pinned facts, vector buckets, assembler cache). Historically
/// the key was always an agent UUID; projects add a second kind under a
/// `project:` prefix. Route new key construction through this so malformed
/// keys are impossible and every namespace-aware call site greps.
///
/// Collision safety: agent keys are bare 36-char UUID strings, which can
/// never parse once prefixed, so `project-` keys cannot collide with them.
/// (Hyphen rather than colon: the key doubles as the vector bucket's
/// on-disk directory name.)
public enum MemoryNamespace: Equatable, Sendable {
    case agent(UUID)
    case project(UUID)

    private static let projectPrefix = "project-"

    /// The string key used across `MemoryDatabase` / search / assembler.
    public var key: String {
        switch self {
        case .agent(let id): return id.uuidString
        case .project(let id): return Self.projectPrefix + id.uuidString
        }
    }

    public init?(key: String) {
        if key.hasPrefix(Self.projectPrefix),
            let id = UUID(uuidString: String(key.dropFirst(Self.projectPrefix.count)))
        {
            self = .project(id)
        } else if let id = UUID(uuidString: key) {
            self = .agent(id)
        } else {
            return nil
        }
    }

    public var isProject: Bool {
        if case .project = self { return true }
        return false
    }
}
